version: "3.4"

services:

  proxy:
    image: nginx:alpine
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
